$schema: 'http://json.schemastore.org/prettierrc'

printWidth: 120
tabWidth: 2
useTabs: false
semi: true
singleQuote: true
jsxSingleQuote: false
trailingComma: none
bracketSpacing: true
jsxBracketSameLine: false
arrowParens: always
proseWrap: preserve
htmlWhitespaceSensitivity: ignore
endOfLine: auto
