branches:
  - name: 1.x
    range: 1.x
    channel: 1.x
  - name: main
plugins:
  - '@semantic-release/commit-analyzer'
  - '@semantic-release/release-notes-generator'
  - - '@semantic-release/changelog'
    - changelogFile: CHANGELOG.md
  - - '@semantic-release/npm'
    - pkgRoot: dist
      tarballDir: dist
  - - '@semantic-release/git'
    - assets:
        - CHANGELOG.md
  - - '@semantic-release/github'
    - assets:
        - path: dist/*.tgz
          label: NPM Package
