{
 "title": "Apollo Server",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" },
   {
    "name": "job",
    "label": "Job",
    "query": "label_values(apollo_server_starting, job)"
   },
   {
    "name": "instance",
    "label": "Instance",
    "query": "label_values(apollo_server_starting, instance)"
   },
   {
    "name": "hostname",
    "label": "Hostname",
    "query": "label_values(apollo_server_starting, hostname)"
   }
  ]
 },
 "panels": [
  {
   "title": "Requests Per Minute",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(apollo_query_started{job=~\"$job\", instance=~\"$instance\"}[5m])) * 60",
     "legendFormat": "Total"
    },
    {
     "expr": "sum(rate(apollo_query_started{job=~\"$job\", instance=~\"$instance\", hostname=~\"$hostname\"}[5m])) by (hostname) * 60",
     "legendFormat": "{{hostname}}"
    }
   ]
  },
  {
   "title": "Failures Per Minute",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(apollo_query_failed{job=~\"$job\", instance=~\"$instance\"}[5m])) * 60",
     "legendFormat": "Total"
    },
    {
     "expr": "sum(rate(apollo_query_failed{job=~\"$job\", instance=~\"$instance\", hostname=~\"$hostname\"}[5m])) by (hostname) * 60",
     "legendFormat": "{{hostname}}"
    }
   ]
  },
  {
   "title": "Average Query Duration",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "(sum(rate(apollo_query_duration_sum{job=~\"$job\", instance=~\"$instance\"}[$__range])) / sum(rate(apollo_query_duration_count{job=~\"$job\", instance=~\"$instance\"}[$__range])))",
     "legendFormat": "Total"
    },
    {
     "expr": "(sum(rate(apollo_query_duration_sum{job=~\"$job\", instance=~\"$instance\", hostname=~\"$hostname\"}[$__range])) by (hostname) / sum(rate(apollo_query_duration_count{job=~\"$job\", instance=~\"$instance\", hostname=~\"$hostname\"}[$__range])) by (hostname))",
     "legendFormat": "{{hostname}}"
    }
   ]
  },
  {
   "title": "Highest Request Rate",
   "type": "table",
   "description": "Operations with the most RPM",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "topk(10, sum(rate(apollo_query_started{job=~\"$job\", instance=~\"$instance\", hostname=~\"$hostname\", operationName!=\"\"}[$__range])) by (operationName) * 60)"
    }
   ]
  },
  {
   "title": "Highest Fail Rate",
   "type": "table",
   "description": "Operations that failed the most",
   "gridPos": { "h": 9, "w": 6, "x": 6, "y": 7 },
   "targets": [
    {
     "expr": "topk(10, sum(apollo_query_failed{job=~\"$job\", instance=~\"$instance\", hostname=~\"$hostname\", operationName!=\"\"}) by (operationName))"
    }
   ]
  },
  {
   "title": "Slow Queries",
   "type": "table",
   "description": "Top 10 slowest queries",
   "gridPos": { "h": 9, "w": 6, "x": 12, "y": 7 },
   "targets": [
    {
     "expr": "topk(10, sum(rate(apollo_query_duration_sum{job=~\"$job\", instance=~\"$instance\", hostname=~\"$hostname\", operationName!=\"\"}[$__range])) by (operationName) / sum(rate(apollo_query_duration_count{job=~\"$job\", instance=~\"$instance\", hostname=~\"$hostname\", operationName!=\"\"}[$__range])) by (operationName))"
    }
   ]
  },
  {
   "title": "Slow Fields Resolution",
   "type": "table",
   "description": "Top 10 fields with the slowest resolutions",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 7 },
   "targets": [
    {
     "expr": "topk(10, sum(rate(apollo_query_field_resolution_duration_sum{job=~\"$job\", instance=~\"$instance\", hostname=~\"$hostname\"}[$__range])) by (fieldName, parentType) / sum(rate(apollo_query_field_resolution_duration_count{job=~\"$job\", instance=~\"$instance\", hostname=~\"$hostname\"}[$__range])) by (fieldName, parentType))"
    }
   ]
  }
 ]
}